<Project>

  <PropertyGroup Label="Build">
    <LangVersion>latest</LangVersion>
    <AnalysisLevel>latest</AnalysisLevel>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Label="Package">
    <Authors>Melosso</Authors>
    <Company>Melosso</Company>
    <Copyright>Copyright © Vaibhav Goyal, Melosso and contributors.</Copyright>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/melosso/DynamicODataToSQL</PackageProjectUrl>
    <PackageIcon>Icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/melosso/DynamicODataToSQL.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReleaseNotes>https://github.com/melosso/DynamicODataToSQL/releases</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup Label="Package References">    
    <PackageReference Include="MinVer" PrivateAssets="all" Version="6.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
